### PR TITLE
minor text edits improvements, CapabilityStatement.rest.security.service

### PR DESCRIPTION
**Pull request by oliveregger**
- minor texte edits

- in addition to text edit, I think the element should be explicitly called CapabilityStatement.rest.security.service

- should the canonical url not point to http://ihe.net/... instead of http://profiles.ihe.net/fhir/ihe.securityTypes/CodeSystem/securityType?  (see also https://github.com/IHE/FormatCode/tree/master)

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
The current approach is to use http://profiles.ihe.net. This is the domain name that we have control over. There is limited support on ihe.net to support redirects of canonical uri

**Comment by oliveregger** [comment]
sorry my comment was maybe not 100% clear. I think the canonical url should be consistent with
https://github.com/IHE/FormatCode/blob/master/input/resources/codesystem-formatcode.xml and start with http://ihe.net or
will codesystem-formatcode.xml also move to profil.ihe.net? The description [here](https://github.com/IHE/FormatCode/tree/master) mentions currently: formal canonical URI http://ihe.net/fhir/ihe.formatcode.fhir/CodeSystem/formatcode

**Comment by JohnMoehrke** [comment]
formatcode canonical URI was defined many years ago, back when we though we could use that for canonical URI. We are working to create one redirect for that.

These things might change... anything in Trial Implementation (or Public Comment) is subject to change.

I would love to use ihe.net; but it seems that technology is going to get in our way.... that or someone smarter comes along and shows us how to do it (hint, hint... feel free to help us Oliver).

**Comment by JohnMoehrke** [comment]
@msmock This pull request looks good to me, please accept it if you agree.

**Comment by msmock** [comment]
Done.

**Pull request merged**
