### PR TITLE
Add metadata support

### LINKED ISSUE #111: Add support for OAuth2 Meta data in IUA
As IUA is based on OAuth there are quite a few items that require configuration on the side of Authorization Clients as well as Authorization Servers, amongst which:
* endpoint URLs for token, authorize, introspect
* endpoint where certificates can be fetched to validate JWT and SAML tokens
* supported authorization grants
* supported access scopes
* supported token format(s)

[RFC8414 OAuth 2.0 Authorization Server Metadata](https://tools.ietf.org/html/rfc8414) provides a standard way to convey such configuration data, agnostic from other base standard constructs such as the FHIR CapabilityStatement. As such, I would propose to add support for RFC814 as an option to the IUA specifications.

### PR DESCRIPTION
**Pull request by joostreuzel**
resolves #111

@JohnMoehrke Note that I introduced a new transaction (Get Authorization Server Metadata). Not knowing the procedure on how the transaction numbers are being assigned, I guessed it would be ITI-103. Please indicate the correct number such that I can correct it before this gets merged.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
are we p;rofiling the transaction? If we are just indicating the transaction is to be used, do we need to have an IHE transaction? For example, we do not have a DNS transaction, yet IHE does use DNS quite a bit.

**Comment by joostreuzel** [comment]
Hi John,

Yes, we are profiling the transaction, making some fields required. Indicating some field values. Adding behavioral requirements...

Regards,
Joost
________________________________

**Comment by JohnMoehrke** [comment]
okay. I reserved 103 for this use

**Review by JohnMoehrke — COMMENTED** [review]
Please don't use visio. Use PlantUML or Powerpoint. Visio licensing is a problem for IHE participants.
Need an interaction diagram at the beginning of the section to show simply request vs response. See 102 use of PlantUML for this. Yes your diagram is a very simple request/response, but it is needed by the template and useful.
Update with the "Editor please add" box as I have done today in other places using a one cell markdown table.

**Comment by joostreuzel** [comment]
Made the requested changes

**Comment by JohnMoehrke** [comment]
@joostreuzel to resolve conflicts and merge

**Pull request merged**
