### PR TITLE
added the supplement framework for Token Introspection

### PR DESCRIPTION
**Pull request by JohnMoehrke**
Addressing issue #106

### CODE REVIEW

**Comment by joostreuzel** [comment]
Working on the edits. A thing I noticed: Access tokens are by definition opaque to authorization clients, according to [OAuth2.1 section 1.4](https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-1.4). The token format is something that needs to be agreed on between the resource server and the authorization server only.

For the specification this means that the JWT, SAML or Introspect options are not relevant for the Authorization Client. It will receive a token (JWT, SAML or some custom format) as bearer token type. It will simply use the token as some random string and post it in Authorization header of type bearer.

This also means that the IHE-SAML authorization header is unnecessary. SAML tokens should be send to resource servers in the same way other tokens are send: as opaque bearer tokens.

In the specification I would like to make the concept of _token format_ explicit. These can be JWT, SAML or a custom format when commonly agreed between resource server and authorization server. Introspect can (optionally) be used for all three formats.

**Comment by joostreuzel** [comment]
To have the authorization server communicate what it option it supports (JWT, SAML, introspect) and provide links to certificate stores required for JWT and SAML token validation, I would recommend to add a [OAuth2 meta-data endpoint](https://tools.ietf.org/html/rfc8414) as an option. I will open a separate issue for that.

**Comment by joostreuzel** [comment]
Additionally on the SAML token option: The SAML grant allows SAML tokens to be used as credentials to obtain an access token.  It is basically an exchange of a SAML token in an access token. This access token may then be in any format (e.g. the JWT format). 

IMHO, the specification should be more clear on the SAML _token_ format. Is this format really necessary? If so, is it also possible to generate SAML tokens from e.g. the code credential flow. As such, I think SAML tokens are independent of SAML grants and should be treated a separate options.

**Comment by JohnMoehrke** [comment]
@joostreuzel I don't know enough about OAuth. I only provided the documentation framework. if the client is not involved then please remove it.

**Comment by joostreuzel** [comment]
@JohnMoehrke I don't have commit access to the branch you created... Is there a process I need to go through?

**Comment by msmock** [comment]
The saml option shall not be confused with the saml grant. That‘s right. IUA currently does not support the saml grant, but allows to use saml as client authentication. The saml token option is just for to use the usual XUA assertion as access token. And yes, we need the Saml token option in the Swiss  EPR.

**Comment by JohnMoehrke** [comment]
> @JohnMoehrke I don't have commit access to the branch you created... Is there a process I need to go through?

@joostreuzel  I just sent you a github invite to IHE/ITI

**Comment by JohnMoehrke** [comment]
> The saml option shall not be confused with the saml grant. That‘s right. IUA currently does not support the saml grant, but allows to use saml as client authentication. The saml token option is just for to use the usual XUA assertion as access token. And yes, we need the Saml token option in the Swiss EPR.
> […](#)
> Am 05.10.2020 um 11:55 schrieb joostreuzel ***@***.***>: ﻿ Additionally on the SAML token option: The SAML grant allows SAML tokens to be used as credentials to obtain an access token. It is basically an exchange of a SAML token in an access token. This access token may then be in any format (e.g. the JWT format). IMHO, the specification should be more clear on the SAML token format. Is this format really necessary? If so, is it also possible to generate SAML tokens from e.g. the code credential flow. As such, I think SAML tokens are independent of SAML grants and should be treated a separate options. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

seems there are a few miscommunications that we likely need to be more clear about. 

1. SAML token used to get an OAuth token
2. OAuth token used to get a SAML Assertion
3. OAuth(SAML) token that carries a SAML assertion
4. ?

**Comment by msmock** [comment]
> > The saml option shall not be confused with the saml grant. That‘s right. IUA currently does not support the saml grant, but allows to use saml as client authentication. The saml token option is just for to use the usual XUA assertion as access token. And yes, we need the Saml token option in the Swiss EPR.
> > […](#)
> > Am 05.10.2020 um 11:55 schrieb joostreuzel _**@**_.***>: ﻿ Additionally on the SAML token option: The SAML grant allows SAML tokens to be used as credentials to obtain an access token. It is basically an exchange of a SAML token in an access token. This access token may then be in any format (e.g. the JWT format). IMHO, the specification should be more clear on the SAML token format. Is this format really necessary? If so, is it also possible to generate SAML tokens from e.g. the code credential flow. As such, I think SAML tokens are independent of SAML grants and should be treated a separate options. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> seems there are a few miscommunications that we likely need to be more clear about.
> 
> 1. SAML token used to get an OAuth token
> 2. OAuth token used to get a SAML Assertion
> 3. OAuth(SAML) token that carries a SAML assertion
> 4. ?

I don't agree. The text clearly says that we use XUA compliant SAML Token as access token. In the text version I started with, these things were all mixed. But the current version is clear about it: No SAML grant type, but a SAML access token is used. We shortly discussed related question in one of our meetings: There are many of OAuth 2.0 extensions defined as RFC and we should not add text blocks arguing why we don't use them. Luckily I could reference the brand new OAuth 2.1 specification which also does not argue, why all the RFC extensions are not used in the core specification.

**Comment by msmock** [comment]
I merged this commit. Although I saw that it is still work in progress with TODO lines. 

The GIT best practice for work in progress is to use a new branch, finish the work and merge afterwards. Since otherwise the stepwise merge is a lot of work. 

Can we do it that way next time?

**Comment by joostreuzel** [comment]
I committed my changes to the add-introspection branch. That may need a new merge into the main.

**Comment by msmock** [comment]
Can you first merge the master branch into your working branch and create a pull request afterward?

**Comment by joostreuzel** [comment]
The confusion with the SAML token arises from section 3.71.6.2.
* This section indicates the use of SAML2 grant types.
* The text mentions that RFC7522 is about "issuing and using SAML 2.0 assertions as access token", which is not true. RFC7522 merely speaks about using SAML Assertions as credentials to obtain an access token. Nothing is said about the access token structure.

My proposal:
* Introduce a separate section for the Get Authorization Token response. The request is different for different grants, but the response is the same in structure
* Move the SAML Assertion, as well as JWT token format to the message semantics section of the token response section
* Remove the section on token types from the Authorization Client. Tokens are opaque to clients. All tokens to be transmitted as Bearer tokens. 
* Consequently: remove the use of IHE-SAML as Authorization token
* As part of the token handling behavior by the resource server refer to the token formats as described in the token response message and indicate the rules on how to deal with them.

**Comment by joostreuzel** [comment]
> Can you first merge the master branch into your working branch and create a pull request afterward?

Done: see #112

**Comment by joostreuzel** [comment]
Given the fact this thread is on token introspection and the discussion moved towards SAML shall we create a new issue for this?

**Pull request merged**
