### PR TITLE
Integrated CP-ITI-1259 into SVCM.

### PR DESCRIPTION
**Pull request by lukeaduncan**
Integrated CP-ITI-1259.

### CODE REVIEW

**Comment by lynnfel** [comment]
Luke, I uploaded an updated SVCM word doc into the SVCM-2022-CPIntegration branch.   It mostly contains editorial updates to TF references, plus one phrase from the  CP that was missing.   All changes are tracked.

**Comment by lukeaduncan** [comment]
It all looks good to me.

**Comment by JohnMoehrke** [comment]
@lukeaduncan did these updates get reflected in the draft SVCM IG? https://github.com/IHE/ITI.SVCM

**Comment by lynnfel** [comment]
Merging this branch for the SVCM republication as PDF (in this cycle)

**Pull request merged**
