### PR TITLE
Ready for committee review

### PR DESCRIPTION
**Pull request by MaryLJ**

### CODE REVIEW

**Comment by lynnfel** [comment]
Mary

This came to my “lfel@charter.net” email address.

If possible, could you change it to felhofer.lynn@gmail.com?   This is what I use for work.

Lynn

**Comment by MaryLJ** [comment]
Reopened

**Comment by JohnMoehrke** [comment]
added Umberto as second ITI-Tech co-chair

**Comment by lynnfel** [comment]
> On Mar 26, 2019, at 10:12 AM, John Moehrke <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> @JohnMoehrke commented on this pull request.
> 
> MOST concerning is that the Public Comment will not know what has changed from the 2.1 version of this supplement. I think Luke was expecting his change tracking to be preserved as the indication in this Public Comment.
Not having participated in the committee calls that preceded this, I was wondering about whether there was an explicit decision about this.    In a separate note to Luke, I recommended at a minimum, updating Open Issue mCSD_8, per your next bullet, to summarize the changes in this version and what it’s trying to achieve.

Lynn

**Comment by JohnMoehrke** [comment]
@lduncan-intrah can you comment on the question around how a Public Comment reviewer would differentiate the facilities changes? Were you expecting word change tracking would be preserved in the public comment version?

**Comment by lduncan-intrah** [comment]
I thought that's how we did it before, but I can add something to the introduction.  Would that be the best place?

**Comment by JohnMoehrke** [comment]
@MaryLJ can we get a new version that preserves the word change-tracking from the version Luke gave you? This is needed as this Public Comment is focused ONLY on those changes.

**Comment by MaryLJ** [comment]
I would need to redo my changes on the original.

**Comment by JohnMoehrke** [comment]
Mary, you might be able to just do a word 'compare' with the original that
Luke provided. That compare operation will result in a change tracking of
ALL changes...

John Moehrke - Architect: Standards - Interoperability, Privacy, and
Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning
HL7 Co-Chair Security WG, FHIR FMG, and FHIR facilitator
FHIR Foundation founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
<John.Moehrke@bylight.com>
https://www.linkedin.com/in/johnmoehrke
https://healthcaresecprivacy.blogspot.com
Postel's Law: Be strict when sending and tolerant when receiving

**Comment by JohnMoehrke** [comment]
issue resolved outside this pull request

**Pull request closed without merging**
